/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   minishell_types.h                                  :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: tmatis <tmatis@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/04/08 11:28:20 by tmatis            #+#    #+#             */
/*   Updated: 2021/05/14 22:54:43 by jmazoyer         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef MINISHELL_TYPES_H

# define MINISHELL_TYPES_H

# include "minishell.h"

/*
** size: the actual size of the buffer.
** position: ths position of the cursor from the back ____[]__ position = 2.
** buff: string allocated on the heap null terminated.
** escape_id: The id of the escape sequence. Generated by get_escape_id;
** manage_history: true of false, tell if the history should be managed
*/

typedef struct s_buffer
{
	int		size;
	int		position;
	char	*buff;
	int		escape_id;
	char	*status;
	t_bool	manage_history;
}				t_buffer;

typedef struct s_redir
{
	int		type;
	char	*file;
}				t_redir;

typedef struct s_command
{
	char	*name;
	char	*cmd;
	t_list	*args;
	t_list	*redirs;
}				t_command;

typedef struct s_var
{
	char	*key;
	char	*data;
}			t_var;

typedef int	t_tube[2];

#endif
