name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install valgrind
      run: sudo apt install -y valgrind
    - name: make
      run: make
    - name: Unit tests
      run: make check
  malloc_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install valgrind
      run: sudo apt install -y valgrind
    - name: make
      run: make
    - name: malloc_test
      run: make check_protection